apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-checks"
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.replicated.com/v1beta1
    kind: Preflight
    metadata:
      name: harbor-enterprise-preflight-checks
    spec:
      analyzers:
        - clusterVersion:
            outcomes:
            - fail:
                when: "< 1.30.0"
                message: The Harbor application requires Kubernetes 1.30.0 or later, and recommends 1.31.0 or later.
                uri: https://www.kubernetes.io
            - warn:
                when: "< 1.31.0"
                message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.31.0 or later.
                uri: https://kubernetes.io
            - pass:
                message: Your cluster meets the recommended and required versions of Kubernetes.
